include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - memo/**
    - openspec/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_print: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
